id: I06A4DE01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:27:32+00:00'
last_modified: '2022-06-08T02:40:55.056721+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20393
  title: འདབ་ཆགས་མི་ཆོས་སུ་བཤད་པ་རིག་པའི་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC2C:
      image_group_id: I5688
      title: ''
      total_pages: 182
      order: 1
      base_file: CC2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
