id: P005381
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20393
  title: འདབ་ཆགས་མི་ཆོས་སུ་བཤད་པ་རིག་པའི་གཏེར་མཛོད
  author: ''
  volumes:
    83a8949fdf084be783fa74fde92196c2:
      image_group_id: I5688
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
